Assignments/chess board
bhs-intro-to-programming/Riley-Pritchard pull request #15
Opened 2022-11-17 23:02 UTC by Riley-Pritchard

2022-11-18 01:21 UTC, gigamonkey requested changes
Left some comments spelling out the suggestion I was trying to make before you computer died. Or you could go with the array that either has one element or is empty but this is more direct. `null` is the a special value in Javascript that means "no value". (It's subtly different from `undefined`. It's probably a mistake that Javascript has both. But typically if you're going to use a value to represent "no value" you use `null` and leave `undefined` for things that don't have a meaning, like the non-value returned by a function that doesn't return anything, if that makes any sense.

2022-11-18 01:21 UTC, gigamonkey commented on assignments/chess-board/code.js
> +let aSelect = []
So, as we were discussing today before your computer got haunted, I'd change this like this:

```suggestion
let selectedPiece = null
```

2022-11-18 01:21 UTC, gigamonkey commented on assignments/chess-board/code.js
> +  if (aSelect !== []) {
Then this can be:

```suggestion
  if (selectedPiece !== null) {
```

2022-11-18 01:21 UTC, gigamonkey commented on assignments/chess-board/code.js
> +    drawText(aSelect, width / 8 * column(x), height / 8 * (row(y) + 1), 'black', 30)
And this:

```suggestion
    drawText(selectedPiece, width / 8 * column(x), height / 8 * (row(y) + 1), 'black', 30)
```

2022-11-18 01:21 UTC, gigamonkey commented on assignments/chess-board/code.js
> +    aSelect.push(board[row(y)][column(x)])
And swap these and change the `aSelect` line to:

```suggestion
    selectedPiece = board[row(y)][column(x)]
    board[row(y)][column(x)] = ''
```

2022-11-18 01:21 UTC, gigamonkey commented on assignments/chess-board/code.js
> +    aSelect.pop(board[row(y)][column(x)])
And here you want to clear out `selectedPiece`

```suggestion
    selectedPiece = null
```

(A note on `pop` even though you don't need to use it if you take these suggestions: it doesn't take any arguments. It just always removes the last item in the list, so `aSelect.pop()` is how you'd call it.)

2022-12-09 22:44 UTC, Riley-Pritchard commented
I don't really want to work on this code, and the comments on this code are old and I don't understand them.

2022-12-10 01:30 UTC, gigamonkey approved these changes
Okay. Go ahead and merge this If you ever want to come back to it you can make a new PR.

2022-12-12 22:55 UTC, merged