Assignments/sudoku
bhs-intro-to-programming/Riley-Pritchard pull request #16
Opened 2022-12-01 23:06 UTC by Riley-Pritchard

2022-12-02 04:24 UTC, gigamonkey requested changes
This is coming together. As I mentioned, I'm going to set up a 2048 environment for you that will let you use key presses to detect arrow keys and you can move this code there and keep going.

2022-12-02 04:24 UTC, gigamonkey commented on assignments/sudoku/code.js
> +  drawText('2', x, y, 'black', 80)
Since you already have the `drawArray` function that can draw the current state of the array on an empty board, I'd not make this function be responsible for actually drawing the 2. Just have this function place a 2 at a random (empty) position in the board and then make sure you call `drawArray` after you've done so.

That would also let you simplify this function into just picking a random empty square, i.e. a pair of values from 0-3 such that board[row][col] is empty. There's some subtleties about doing that in the most efficient way but there are plenty of ways that work fine.

2022-12-02 04:24 UTC, gigamonkey commented on assignments/sudoku/code.js
> +const move = (x) => {
If you move this code to the 2048 environment I'm setting up, you'll know from the key event which direction you want to move but the basic logic will be the same.

2022-12-02 04:24 UTC, gigamonkey commented on assignments/sudoku/code.js
> +random2()
This sequence, with one small change should probably be broken out into a separate function.

```javascript
clear()
drawBoard()
random2()
drawArray()
```

This is basically what you want to do both at the beginning of the game and after every move: clear the screen, draw the grid, fill a random empty square with a 2 (or sometimes a 4, at least in the original game), and then draw the numbers where they belong.

2022-12-02 04:24 UTC, gigamonkey commented on assignments/sudoku/code.js
> +drawBoard()
In general you should define all the functions first and then after they're all defined, make the actual calls at the bottom of the file so you can see what actually happens in what order. In this case I think you'll see, if you do that, that the sequence of calls you make at the beginning of the game is almost the same as the sequence of calls you make after each move which suggest that you might want to wrap that sequence up in its own function.

2022-12-02 19:07 UTC, gigamonkey commented
Here you go: https://intro.gigamonkeys.com/assignments/2048/

2022-12-09 22:57 UTC, Riley-Pritchard commented
I'm no longer using this code since I switched to the 2048 environment.

2022-12-10 01:32 UTC, gigamonkey approved these changes
Great. Go ahead and merge this then.

2022-12-12 22:55 UTC, merged