Updating assignments/game-of-life/code.js
bhs-intro-to-programming/Riley-Pritchard pull request #18
Opened 2022-12-05 23:31 UTC by Riley-Pritchard

2022-12-05 23:32 UTC, Riley-Pritchard commented
@gigamonkey It is giving me an error code for the last line of code and I have no clue why.

2022-12-06 03:21 UTC, gigamonkey requested changes
I assume the error is something about "unexpected end of input" or something? Look at how the definition `const whatLives` is indented? See how it's indented relative to where the previous function `const neighbors` is? That's because the `neighbors function is never closed so everything else is part of it and there aren't enough closing curly braces. So you need to make sure all the open curly braces in `neighbors` are matched by an appropriately placed closing curly brace.

2022-12-11 18:19 UTC, gigamonkey requested changes
Closer and closer! Left you a pointer of; happy to talk about it on Monday if you'd like a fuller explanation.

2022-12-11 18:19 UTC, gigamonkey commented on assignments/game-of-life/code.js
> +}
This is getting close. However you almost certainly need to make a copy of the state of the world which you use to check `neighbors` because if you go through and change the values of the cells in `b` at the same time as you're using it to check neighbors that will mess up the computation of the correct state of the neighboring cells.

Unfortunately there's not a trivial way to copy a 2d array like this so you'll probably need to write a function to do that.

2023-01-03 23:00 UTC, merged