Assignments/boolean birds
bhs-intro-to-programming/Riley-Pritchard pull request #2
Opened 2022-09-08 22:19 UTC by Riley-Pritchard

2022-09-08 23:42 UTC, gigamonkey requested changes
Mostly to practice the PR flow, can you make the style fixes I suggested? When you change the code and run/save it will be automatically added to this PR and then I can approve it and you can merge.

2022-09-08 23:42 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +const isFlobbyBird =(isRed, isSpotted) => isRed && isSpotted
```suggestion
const isFlobbyBird = (isRed, isSpotted) => isRed && isSpotted;
```
That shows some very small changes I'd make to that line of code. I'll talk about how to read these soon. But basically I'd add a space after the `=` and add a `;` at the end.

2022-09-08 23:42 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +  return s1==='Flobby' || s1 === 'Bloggy'
In addition to adding a space between the `=` and the arguments lists in all these functions, you should consistently add spaces around most operators (`!` is maybe the only one that is directly up against it's operand.) These are just style guidelines but using consistent style makes code a lot easier to read.

2022-09-08 23:42 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +  return s1==='Flobby' || s1 === 'Bloggy'
These lines should also end in `;`. Not something we talked about and not technically required but again, a matter of my preferred style. And for now I'm going to ask you all to use my preferred style since the main rule of coding style is to follow the existing standard when you join a team.

2022-09-13 21:46 UTC, Riley-Pritchard commented on assignments/boolean-birds/code.js
> +  return s1==='Flobby' || s1 === 'Bloggy'
@gigamonkey I made the changes, you said to run/save and I'm not sure what you mean by that. Hopefully it saved and you can see it.

2022-09-16 00:07 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +  return s1==='Flobby' || s1 === 'Bloggy'
Yeah. You did it right. I think in future I'm going to ask folks to hit the request re-review thing. (I had forgotten about it until recently.)

![2022-09-15 at 5 06 PM](https://user-images.githubusercontent.com/250053/190529363-50707e06-3e1d-49d8-b55c-432cdcf5d548.png)

2022-09-16 00:07 UTC, gigamonkey approved these changes
Looks good. Ship it!

2022-09-16 22:20 UTC, merged