Assignments/images challenge
bhs-intro-to-programming/Riley-Pritchard pull request #5
Opened 2022-09-21 22:23 UTC by Riley-Pritchard

Most of the code works except for the checkerboard one and the one with the lines. The checkerboard one works only with certain numbers including 3, 5, 7, but not 9??  I don't really know how to fix it but I'm working on it. The line one is confusing because I don't really understand what is going on in the image in gallery, and my code isn't really working so I'm still working on that. There is also one more image that I haven't started working on yet.

2022-09-22 04:16 UTC, gigamonkey reviewed
Left a few comments. Looks like you're on a good track. If you ask for help tomorrow I can probably explain what's going on with the "Not really curved" image.

2022-09-22 04:16 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +    let x = 0 + r * 2
Note that since `r` never changes this value also never changes. That means you can move it above the loop and can also change the `let` to a `const`. I'd also rename it `d` since if `r` is the radius, this is the diameter. And finally, you can take out the `0 +` since that doesn't do anything. ;-)

2022-09-22 04:16 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +    let y = height / 2
This can also be moved outside the loop and be made `const`.

2022-09-22 04:16 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +const drawSpicyCircleLine = (y, r, color) => {
Not clear that `color` needs to be an argument here. Why not just make a variable inside the function and start it out as `'red'`. Because the other logic kind of depends on it being `'red'` so you don't want to leave it up to the caller of this function to pass in a specific value you need.

2022-09-22 04:16 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +    let x = 0 + r * 2
Same comment as in earlier function.

2022-09-22 04:16 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  for (let r = width / 2; c === c; r = r - width / 2 / c) {
Do you know the term "tautology"? It's a statement that is always true. `c === c` is a tautology which means this is an infinite loop unless I'm quite mistaken.

2022-09-22 04:16 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  for (let r = width / 2; c === c; r = r - width / 2 / c) {
This is also an example of the idea we talked about in class. I'd try to write this as 

```javascript
for (let i = 0; i < someNumber; i++) {
```

where `someNumber` is a value that I've computed which is the number of circles I want to draw. In this case it's something like `Math.floor(width / (2 * r))`, i.e. the number of circles that will fit across the drawing area.

Then inside the loop do whatever math you need, using `i` to compute the values like what the x value of the circle should be.

2022-09-22 21:58 UTC, Riley-Pritchard commented on assignments/images-challenge/code.js
> +  for (let r = width / 2; c === c; r = r - width / 2 / c) {
Well if I want someNumber to equal the number of circles I want to draw it would be c < c which just doesn't work. My infinite loop works though, are infinite loops not good to have? I did change it to (let r = width / 2;; r = r - width / 2 / c) but I'm not sure if that is any better. I made it c === c because I don't think it needs to have a condition to work so by making it c === c then there isn't a condition because it is always true.

2022-09-22 22:01 UTC, Riley-Pritchard commented on assignments/images-challenge/code.js
> +    let x = 0 + r * 2
Will it help to change the code even if I already wrote it? For the circle ones I just copy and pasted it from my circle line, and reused the code so I'm not actively writing out r * 2 every time.

2022-09-22 22:26 UTC, Riley-Pritchard commented on assignments/images-challenge/code.js
> +const drawSpicyCircleLine = (y, r, color) => {
I tried adjusting it but it just made the whole thing red without the alternating colors, just a big red circle, so I'm not really sure how to do that.

2022-09-27 00:02 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +    let x = 0 + r * 2
Yeah, the idea is good. The point is that as the code stands the computer does the work of computing the value of `x` every iteration of the loop and you only need to compute it once before the loop. If it's inside the loop the computer does extra work and probably more important the human reader has to decipher it to realize that it's not actually changing even though it's inside the loop.

2022-09-27 00:08 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +const drawSpicyCircleLine = (y, r, color) => {
I was suggesting something like this:

```suggestion
const drawSpicyCircleLine = (y, r) => {
  let color = 'red';
```

I.e. make it a local variable but not a parameter. (And then you change the call to `drawSpicyCircleLine` to just pass the y value and the radius.)

2022-09-27 00:08 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  for (let r = width / 2; c === c; r = r - width / 2 / c) {
Well, if you wanted a condition that was always true you could just write `true`. I.e.

```javascript
for (let r = width / 2; true ; r = r - width  / 2 / c) {
```

But the problem with infinite loops is they never end. So your program can never do anything else. It maybe that you're running this function and it draws the right image but then is infinitely drawing circles with negative radius. Or possibly it's actually crashing because the underlying grahpics code barfs when you pass it a negative radius. So it may look like it's working but it's not working for the right reason.

2022-09-27 00:14 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  for (let r = width / 2; c === c; r = r - width / 2 / c) {
Indeed. I just tried your code and if I call your function from the REPL I get this error message (after it draws the image).

`IndexSizeError: Failed to execute 'ellipse' on 'CanvasRenderingContext2D': The major-axis radius provided (-23.6) is negative. (line 45, column 7) of http://localhost:8080/assignments/simple-draw/frame/framework.js`

I noticed you changed the loop to have no condition:

```
for (let r = width / 2; ; r = r - width  / 2 / c) {
```

That's another infinite loop as the default condition, if none is specified, is `true`.

2022-09-27 00:18 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +const drawSpicyCircleLine = (y, r, color) => {
(Sorry broke the threading: see https://github.com/bhs-intro-to-programming/Riley-Pritchard/pull/5/files#r980611064)

2022-09-28 21:38 UTC, Riley-Pritchard commented
>

2022-09-28 22:19 UTC, Riley-Pritchard commented
Ok so I changed some of the code to use i = 0; i < #; i++  so thats great. I still don't know what's up with my checkerboard, and I'm not really sure how to write, i = what i equaled at the final time the code ran, which I need for the frame. Everything else works great though.

2022-09-29 03:21 UTC, gigamonkey requested changes
Left a comment to point you in the right direction. Happy to talk more if that's not enough of a clue.

2022-09-29 03:21 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  for (let j = 1 ; d * j < height - (d); j++) {
What if instead of having your condition be `d * j < height - d` you figured out how many circles you were going to draw vertically:

```javascript
const verticalCircles = Math.floor(height / d);
```

Then you could loop like:

```javascript
for (let j = 0; j < verticalCircles; j++) {
  const y = d + d * j; // I'm not sure that's exactly right but something like that.
```

Then you know that the top row is when `j` is 0 and the bottom row is when `j` is `verticalCircles - 1`. Does that help?

2022-10-06 02:40 UTC, gigamonkey requested changes
Left some more comments on the new code.

2022-10-06 02:40 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +          n = n + 0.0000000000001
Like we talked about in class, this is really not the right way to do this. It *looks* like it works because the extra square is getting drawn mostly outside the drawing area or something. But the right thing to do is to figure out a more reliable way to determine for each position in a checkerboard what color the square should be.

2022-10-06 21:55 UTC, Riley-Pritchard commented on assignments/images-challenge/code.js
> +  for (let j = 0; j < verticalCircles - 1; j++) {
@gigamonkey I switched it to the way you said, but the reason why was to just center it better.

2022-10-06 21:58 UTC, Riley-Pritchard commented on assignments/images-challenge/code.js
> +          n = n + 0.0000000000001
Do you want me to change it to something more legitimate? I'm not really sure how I would do that, I tried doing it conventionally before I came up with this solution and I couldn't figure it out.

2022-10-24 00:10 UTC, gigamonkey approved these changes
Looks pretty good! You can go ahead and merge this and we'll start on some new projects this week.

2022-10-24 22:23 UTC, merged