Assessments/unit 01
bhs-intro-to-programming/Riley-Pritchard pull request #6
Opened 2022-09-30 22:33 UTC by Riley-Pritchard

2022-10-03 22:33 UTC, Riley-Pritchard commented
@gigamonkey it isn't giving me the option to request so I'm just commenting this so you'll see it.

2022-10-06 00:21 UTC, gigamonkey requested changes
At some point you should probably fix all of these, just to make sure you understand my comments. But for this coming Friday, make sure you know how to write functions like the first five problems involving numeric expressions.

2022-10-06 00:21 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  if (c / 2 < d / 2) {
You flipped the logic: you want to return the smaller of the two values so if `c / 2 < d /2` you want to return `c / 2`.

Another way to write this without an `if` statement would be to use `Math.min`:

```javascript
  return Math.min(c / 2, d / 2)
```

Or the way I'd actually write it, using more descriptive argument names and only doing the division once, after I've figured out which one I need to divide:

```javascript
  return Math.min(width, height) / 2;
```

2022-10-06 00:21 UTC, gigamonkey commented on assessments/unit-01/code.js
> +const offset = (w, x1, x2) => {
This function is only supposed to take two arguments so I'm not sure what x1 and x2 are. Another benefit of using meaningful names is that it makes it easier to match up the arguments to the description of the function. In this case the description was:

> takes two arguments, the width, in pixels, of a drawing area and the width of a figure (guaranteed to be less than the total width, also in pixels)

So we know there should be two arguments and they could reasonably be named `width` and `figureWidth` or something like that. Then the math is just `(width - figureWidth) / 2`. (I.e. `width - figureWidth` is the total extra horizontal space and then divide by two to figure out how much belongs on the left of the figure to center it.)

2022-10-06 00:21 UTC, gigamonkey commented on assessments/unit-01/code.js
> +const canSleepIn = (s) => {
Another one where you need to read the description of the arguments and map them to variables in the argument list:

> two boolean arguments, the first saying whether it's a weekday and the second saying whether you're on vacation

So I'd expect an argument list like `(weekday, vacation)` and then a body that uses boolean operators like `&&`, `||`, and `!` to combine the two boolean values. In this case it would be `!weekday || vacation`

2022-10-06 00:21 UTC, gigamonkey commented on assessments/unit-01/code.js
> +const canGoToProm = (s, s1) => {
Again, need to map the description to arguments more carefully: there should be three arguments, named something like `(isSenior, invitedBySenior, promExclusionList)`.

2022-10-06 00:21 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return s === 'isSenior' || s === 'invitedBySenior' && s1 !== 'promExclusionList'
If you replaced all the `===` expressions with just references to the arguments I proposed before this is almost right. It would look like:

```javascript
isSenior || invitedBySenior  && !promExclusionList
```

That looks about right except (and I realized I maybe never talked about the operator precedence of these operators) `&&` has higher precedence than `||` just like `*` is higher than `+` so this is the same as:

```javascript
isSenior || (invitedBySenior  && !promExclusionList)
```

To get the correct order you need to add explicit grouping parentheses:

```javascript
(isSenior || invitedBySenior)  && !promExclusionList
```

2022-10-06 00:21 UTC, gigamonkey commented on assessments/unit-01/code.js
> +const getsSpeedingTicket = (a, s) => {
Similar problem: when the description says the argument is a boolean that means it's going to be either `true` or `false`. So instead of `s === 'grouchy'` which assumes `s` is a string containing a particular value, you just want to use `s`. (Though it would be better if you named the variable to be meaningful, like perhaps: `grouchy`.)

2022-10-06 00:21 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return Math.abs(a - b) < Math.abs(a - c)
Close but this is telling us whether `a` is closer to `b` than `a` is to `c` whereas what the description asked for is whether `a` is closer to `c` than `b` is to `c`.

2022-10-06 00:21 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  s.substring(s.length / 2)
This is actually just another way of getting the second half. The first argument to `substring` is always the starting position. (And the second argument defaults to the length of the string if not provided.) So this needs to be `s.substring(0, s.length / 2)` to start at 0 and go up to the midpoint.

2022-10-06 00:21 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return s.substring(s.length - 1).toUpperCase() + s.substring(s.length - 1).toLowerCase()
Good. A slightly more concise alternative is:

```javascript
return s[s.length - 1].toUpperCase() + s[s.length - 1].toLowerCase()
```

2022-10-06 00:21 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  let z = 0
This is fine but I'd really encourage you to use meaningful names. What does `z` stand for? I'd use `count` or at least `c` which can stand for `count`.

2022-10-06 00:21 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  if (s.search(/[x]/) !== -1) {
This is correct. I'll point out that whenever you have code of the form:

```javascript
if (condition) { 
  return true
} else {
  return false
}
```

you can simplify it to just:

```javascript
return condition
```

I.e. `condition` (whatever expression it is) is already a boolean value so you can just return it.

So is this case just:

```javascript
return s.search(/[x]/) !== -1
```

2022-10-06 00:21 UTC, gigamonkey commented on assessments/unit-01/code.js
> +    a - (x) ** 2
This needs a variable to accumulate the sum (similar to `z` in `countXs` and then you need to update it in the loop. Something like:

```javascript
let sum = 0;
```

and then in the loop:

```javascript
sum = sum + x ** 2;
```

2022-10-15 03:22 UTC, gigamonkey approved these changes
All the new code looks good. I left a few small comments. You can merge this.

2022-10-15 03:22 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return s.substring(s.length / 2, s.length)
This is fine and correct but slightly more stylish would be to use the fact that the second argument defaults to the length of the string if omitted and just write:

```javascript
  return s.substring(s.length / 2);
```

2022-10-15 03:22 UTC, gigamonkey commented on assessments/unit-01/code.js
> +      c = c
This line doesn't really do anything. It just assigns the current value of `c` to `c`. So you could leave this line out without changing anything. Which would then leave the `else` clause empty which is fine but at that point you can just drop it. So you'd just have:

```javascript
if (s[i] === 'x') {
  c++
}
```

2022-10-15 03:22 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return (s.search(/[x]/) !== -1)
Yup, that works. I was expecting a more laborious `for` loop looking at each character and returning `true` if you found an `x`. Which it's worth knowing how to write but this is certainly correct and concise.

2022-10-18 21:51 UTC, Riley-Pritchard commented on assessments/unit-01/code.js
> +  return (s.search(/[x]/) !== -1)
Ok thanks. If you could just approve the PR so I can merge it that would be great! Thanks @gigamonkey

2022-10-19 21:50 UTC, merged